### PR TITLE
Fix allowed responses

### LINKED ISSUE #54: Allowed responses are broken
The allowed responses are processed after the `Keyboard` object is created, and therefore not taken into account.

See:

- https://github.com/open-cogsci/osweb/blob/1.3/src/js/osweb/items/generic_response.js#L281

### PR DESCRIPTION
**Pull request by smathot**
Actually fixes #54, not #28 (the fix to that issue actually introduced this regression).

### CODE REVIEW

File: src/js/osweb/items/generic_response.js [hunk 1]
```diff
@@ -126,16 +126,14 @@ export default class GenericResponse extends Item {
...
-    this._keyboard._set_config(final_duration, this._allowed_responses)
+    this._final_duration = (this._timeout !== -1) ? this._timeout : this._duration
   }
 
   /** Prepare the system for a mouseclick duration interval. */
   prepare_duration_mouseclick () {
     // Prepare a mouseclick duration.
     this._mouse = new Mouse(this.experiment)
-    var final_duration = (this._timeout !== -1) ? this._timeout : this._duration
-    this._mouse._set_config(final_duration, this._allowed_responses, false)
```
Comment (dschreij) [inline src/js/osweb/items/generic_response.js:138]: Are these and kb._set_config still necessary after this change? If not, I would clean them up/remove them too.

**Review by dschreij — APPROVED** [review]

File: src/js/osweb/items/generic_response.js (hunk 1 above)
Comment (smathot) [reply src/js/osweb/items/generic_response.js:138]: Yes, they are just called later on.
