### PR TITLE
Fix setting the correct variable in the touch_response

### LINKED ISSUE #22: Response items do not suffix item names to response variables
touch_response items do not store the usual vars that an item logs, such as `correct_<item_name>` or `response_time_<item_name>`. See https://forum.cogsci.nl/discussion/comment/19615/#Comment_19615 for more info and an experiment that demonstrates this.

### PR DESCRIPTION
**Pull request by smathot**
This should fix setting the `correct` variable in `touch_response` items, which also fixes #22.

### CODE REVIEW

File: src/js/osweb/items/generic_response.js [hunk 1]
```diff
@@ -262,7 +261,7 @@ export default class GenericResponse extends Item {
       this.experiment.vars.acc = this.experiment.vars.accuracy
       this.experiment.vars.average_response_time = Math.round(this.experiment.vars.total_response_time / this.experiment.vars.total_responses)
       this.experiment.vars.avg_rt = this.experiment.vars.average_response_time
-      this.experiment.vars.set('correct_' + this.name, this.vars.correct)
+      this.experiment.vars.set('correct_' + this.name, this.experiment.vars.correct)
```
Comment (dschreij) [inline src/js/osweb/items/generic_response.js:264]: I always though these were identical. Or rather, that if the variable wasn't found in the local var store, it automatically also looks in the global var store.

**Review by dschreij — APPROVED** [review]

File: src/js/osweb/items/generic_response.js (hunk 1 above)
Comment (smathot) [reply src/js/osweb/items/generic_response.js:264]: This is how it works in an `inline_javascript` item, because there we use a proxy for the vars object. But for the regular `vars` object, only `vars.get()` uses this fallback behavior.
